title: CC Unipampa
description: Links
url: https://cienciadacompunipampa.github.io
remote_theme: oAGoulart/lesta
#theme: lesta
plugins:
  - jekyll-seo-tag

exclude: [
  Gemfile.lock,
  lesta.gemspec,
  README.md,
  CHANGELOG.md,
  Gemfile, vendor, scripts
]
